# Generated by Django 4.0.2 on 2022-02-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(verbose_name='타임스탬프')),
                ('content', models.TextField(verbose_name='시간에 따른 스크립트 내용')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_id', to='video.video', verbose_name='동영상 id')),
            ],
            options={
                'verbose_name_plural': '스크립트',
                'db_table': 'script',
            },
        ),
    ]
